import { Inter } from "next/font/google";
import Navbar from "../../components/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Home",
	description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
